version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'v2-deps-{{ .Branch }}-'
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - tmp
  actions.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'actions.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/actions.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  aliasing.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'aliasing.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/aliasing.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  assertions.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'assertions.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/assertions.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  connectors.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'connectors.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/connectors.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  cookies.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'cookies.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/cookies.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  cypress_api.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'cypress_api.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/cypress_api.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  files.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'files.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/files.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  local_storage.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'local_storage.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/local_storage.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  location.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'location.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/location.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  misc.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'misc.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/misc.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  navigation.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'navigation.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/navigation.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  network_requests.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'network_requests.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/network_requests.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  querying.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'querying.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/querying.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  spies_stubs_clocks.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'spies_stubs_clocks.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/spies_stubs_clocks.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  traversal.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'traversal.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/traversal.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  utilities.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'utilities.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/utilities.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  viewport.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'viewport.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/viewport.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  waiting.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'waiting.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/waiting.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  window.spec.js:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress test 'window.spec.js'
          command: >-
            $(npm bin)/cypress run --spec cypress/integration/tests to
            run/window.spec.js
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - actions.spec.js:
          requires:
            - build
      - aliasing.spec.js:
          requires:
            - build
      - assertions.spec.js:
          requires:
            - build
      - connectors.spec.js:
          requires:
            - build
      - cookies.spec.js:
          requires:
            - build
      - cypress_api.spec.js:
          requires:
            - build
      - files.spec.js:
          requires:
            - build
      - local_storage.spec.js:
          requires:
            - build
      - location.spec.js:
          requires:
            - build
      - misc.spec.js:
          requires:
            - build
      - navigation.spec.js:
          requires:
            - build
      - network_requests.spec.js:
          requires:
            - build
      - querying.spec.js:
          requires:
            - build
      - spies_stubs_clocks.spec.js:
          requires:
            - build
      - traversal.spec.js:
          requires:
            - build
      - utilities.spec.js:
          requires:
            - build
      - viewport.spec.js:
          requires:
            - build
      - waiting.spec.js:
          requires:
            - build
      - window.spec.js:
          requires:
            - build
